name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: ${{ github.ref_name }} # Maps branch to environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        echo "AWS_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV

    - name: Build and Push Frontend Image
      run: |
        docker build -t <ecr_repository_uri>/${{ env.ENVIRONMENT }}/frontend:latest ./frontend
        docker push <ecr_repository_uri>/${{ env.ENVIRONMENT }}/frontend:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t <ecr_repository_uri>/${{ env.ENVIRONMENT }}/backend:latest ./backend
        docker push <ecr_repository_uri>/${{ env.ENVIRONMENT }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy ECS Services
      run: |
        aws ecs update-service --cluster ${{ env.ENVIRONMENT }}-cluster \
          --service backend-service \
          --force-new-deployment
        aws ecs update-service --cluster ${{ env.ENVIRONMENT }}-cluster \
          --service frontend-service \
          --force-new-deployment
